name: Release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create package artifact
        run: npx @anthropic-ai/mcpb pack
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.mcpb"
          draft: true
