name: Release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  id-token: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create package artifact
        run: npx @anthropic-ai/mcpb pack
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.mcpb"
          draft: true
      - name: Update fileSha256 in server.json
        run: |
          SHA256_HASH=$(sha256sum "mcp-youtube-transcript.mcpb" | awk '{print $1}')
          jq --arg hash "$SHA256_HASH" '.packages[0].fileSha256 = $hash' server.json > server_tmp.json
          mv server_tmp.json server.json
          cat server.json
      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/v1.2.3/mcp-publisher_1.2.3_linux_amd64.tar.gz" | tar xz mcp-publisher
      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc
      - name: Publish to MCP Registry
        run: ./mcp-publisher publish
